### ISSUE TITLE
git-like

### ISSUE THREAD

**Issue by pimarin** [mesocentre-clermont-auvergne/formation_fair#1]
** GIT formation**
```
L'objectif est d'initier à la notion de gestion et versionnage de code, en présentant tous les avantages de git et ces utilisations dans le cadre de github et gitlab par exemple.
Une premiere approche graphique des interface en montrant les possibilités (versionnage, site web, publication, gestion de projets...), afin d'intéresser les utilisateurs.
Dans un second temps nous verrons la partie ligne de commande avec application rapide lors des TP

```
1. Présentation théorique
    - Notions de version et d'archivage
    - Notion de partage
    - Présentation de Github
    - Présentation de Gitlab
    - Discussion des Git-like
    - Introduction à Git ligne de commande
2. Activité pratique
    - Mise en pratique de l'utilisation de git en ligne de commande
        - creation de dépôts
        - récupération de dépôts
        - notion de branch
        - gestion de pull request

**Comment by nagoue** [comment]
https://hub.mesocentre.uca.fr/docs/cluster/accesGitHub/
à compléter pour gitlab
