### ISSUE TITLE
Vérification TP Jupyter

### ISSUE THREAD

**Issue by pimarin** [mesocentre-clermont-auvergne/formation_fair#42]

**Comment by nagoue** [comment]
Dans la section "Make your own kernel to work" : 

- Je préciserais que les commandes sont passées dans un terminal et non un notebook et mettre les commandes dans un bloc de codes 
```bash
[xxx@hpcphi01 ~]$ mamba install -c conda-forge nb_conda_kernels
[xxx@hpcphi01 ~]$ mamba create -n env_py38 python=3.8 numpy matplotlib pandas scipy dask
[xxx@hpcphi01 ~]$ mamba activate env_py38
[xxx@hpcphi01 ~]$ mamba install ipykernel jupyter_client
[xxx@hpcphi01 ~]$ python -m ipykernel install --user --name env_py38 --display-name "kernel_python_3.8"
```

- Install a Python Kernel with Python3.10
cependant c'est un `create -n env_py38 python=3.8` qui est créé. Alors 3.10 ou 3.8 ?

- La commande `mamba install -c conda-forge nb_conda_kernels` ne fonctionne pas 
    - ni depuis le terminal hpcphi de jupyter: 
  
`RuntimeError: Download error (28) Timeout was reached [https://repo.anaconda.com/pkgs/main/noarch/repodata.json]
    Failed to connect to repo.anaconda.com port 443 after 7051 ms: Connection timed out `

    - ni depuis une connexion classique depuis en ssh:

`EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: /opt/core/conda-4.12.0
  uid: 5032
  gid: 5000
`

**Comment by pimarin** [comment]
J'ai fixé le problème

**Comment by pimarin** [comment]
```
Follow the guide from the mesocentre to install your kernel: https://hub.mesocentre.uca.fr/docs/cluster/applis/jupyterhub/
```
1. Install a Python Kernel with python 3.10
```
conda create -n env_py3.10 python=3.10 numpy ipykernel jupyter_client
conda activate env_py3.10
python -m ipykernel install --user --name env_py3.10 --display-name "kernel_python_3.10"
```

2. Install a R kernel with r-base 4.2

```
conda create --name env-r4.2 r-base=4.2 r-essentials r-irkernel jupyter_client
conda activate env-r4.2
R -e "IRkernel::installspec(name='env-r4.2', displayname='env_R_4.2', user=TRUE)"
```

Test available kernels
```
conda activate env_py3.10
jupyter kernelspec list
```
