### ISSUE TITLE
Vérifier les liens du readme

### ISSUE THREAD

**Issue by nagoue** [mesocentre-clermont-auvergne/formation_fair#44]
Pour snakemake, le cours n'est pas la dernière version, et le lien vers le TP n'existe pas.

**Comment by nagoue** [comment]
Il y a une section fair-environnement (dans laquelle j'ai les MAJ snakemake) et où il n'y a que snakemake (?)  et il y a un fair-workflow.
@pimarin, qu'est-ce que tu préfères ?

**Comment by pimarin** [comment]
Je me dis que fair-workflow est plus parlant non ?

P. MARIN

Le 7 juil. 2023 à 10:22, Nadia Goué ***@***.***> a écrit :

﻿

Il y a une section fair-environnement (dans laquelle j'ai les MAJ snakemake) et où il n'y a que snakemake (?) et il y a un fair-workflow.
@pimarin<https://github.com/pimarin>, qu'est-ce que tu préfères ?

**Comment by nagoue** [comment]
Si tu veux. Je te laisse faire le merge. 


De: "pimarin" ***@***.***> 
À: "mesocentre-clermont-auvergne/formation_fair" ***@***.***> 
Cc: "Nadia GOUE" ***@***.***>, "Author" ***@***.***> 
Envoyé: Vendredi 7 Juillet 2023 11:51:51 
Objet: Re: [mesocentre-clermont-auvergne/formation_fair] Vérifier les liens du readme (Issue #44) 



Je me dis que fair-workflow est plus parlant non ? 

P. MARIN 

Le 7 juil. 2023 à 10:22, Nadia Goué ***@***.***> a écrit : 



Il y a une section fair-environnement (dans laquelle j'ai les MAJ snakemake) et où il n'y a que snakemake (?) et il y a un fair-workflow. 
@pimarin<https://github.com/pimarin>, qu'est-ce que tu préfères ?

**Comment by pimarin** [comment]
merged
